//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail
    {
        public int id_bill_detail { get; set; }
        public int id_goods_attributes { get; set; }
        public int quantity { get; set; }
        public int id_bill { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual goods_to_attributes goods_to_attributes { get; set; }
    }
}
