//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CapstoneEnitity : DbContext
    {
        public CapstoneEnitity()
            : base("name=CapstoneEnitity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attribute> attributes { get; set; }
        public DbSet<attributes_set> attributes_set { get; set; }
        public DbSet<bill> bills { get; set; }
        public DbSet<bill_detail> bill_detail { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<good> goods { get; set; }
        public DbSet<goods_to_attributes> goods_to_attributes { get; set; }
        public DbSet<group_goods_quantity_stock> group_goods_quantity_stock { get; set; }
        public DbSet<group_outpound_goods> group_outpound_goods { get; set; }
        public DbSet<outbound> outbounds { get; set; }
        public DbSet<role_staff> role_staff { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<state_bill> state_bill { get; set; }
        public DbSet<state_goods> state_goods { get; set; }
        public DbSet<group_agency_goods> group_agency_goods { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int sp_attributes_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_delete", idParameter);
        }
    
        public virtual int sp_attributes_insert(string id_attributes, string name, string img, Nullable<int> id_attributeset, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at, Nullable<byte> active)
        {
            var id_attributesParameter = id_attributes != null ?
                new ObjectParameter("id_attributes", id_attributes) :
                new ObjectParameter("id_attributes", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var id_attributesetParameter = id_attributeset.HasValue ?
                new ObjectParameter("id_attributeset", id_attributeset) :
                new ObjectParameter("id_attributeset", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_insert", id_attributesParameter, nameParameter, imgParameter, id_attributesetParameter, create_atParameter, update_atParameter, activeParameter);
        }
    
        public virtual ObjectResult<sp_attributes_select_Result> sp_attributes_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_attributes_select_Result>("sp_attributes_select");
        }
    
        public virtual int sp_attributes_set_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_set_delete", idParameter);
        }
    
        public virtual int sp_attributes_set_insert(string id_attributeset, string name, string sub_name, Nullable<byte> checkimg, Nullable<int> id_categories, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_attributesetParameter = id_attributeset != null ?
                new ObjectParameter("id_attributeset", id_attributeset) :
                new ObjectParameter("id_attributeset", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var sub_nameParameter = sub_name != null ?
                new ObjectParameter("sub_name", sub_name) :
                new ObjectParameter("sub_name", typeof(string));
    
            var checkimgParameter = checkimg.HasValue ?
                new ObjectParameter("checkimg", checkimg) :
                new ObjectParameter("checkimg", typeof(byte));
    
            var id_categoriesParameter = id_categories.HasValue ?
                new ObjectParameter("id_categories", id_categories) :
                new ObjectParameter("id_categories", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_set_insert", id_attributesetParameter, nameParameter, sub_nameParameter, checkimgParameter, id_categoriesParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_attributes_set_select_Result> sp_attributes_set_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_attributes_set_select_Result>("sp_attributes_set_select");
        }
    
        public virtual int sp_attributes_set_update(Nullable<int> id, string id_attributeset, string name, string sub_name, Nullable<byte> checkimg, Nullable<int> id_categories, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_attributesetParameter = id_attributeset != null ?
                new ObjectParameter("id_attributeset", id_attributeset) :
                new ObjectParameter("id_attributeset", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var sub_nameParameter = sub_name != null ?
                new ObjectParameter("sub_name", sub_name) :
                new ObjectParameter("sub_name", typeof(string));
    
            var checkimgParameter = checkimg.HasValue ?
                new ObjectParameter("checkimg", checkimg) :
                new ObjectParameter("checkimg", typeof(byte));
    
            var id_categoriesParameter = id_categories.HasValue ?
                new ObjectParameter("id_categories", id_categories) :
                new ObjectParameter("id_categories", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_set_update", idParameter, id_attributesetParameter, nameParameter, sub_nameParameter, checkimgParameter, id_categoriesParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_attributes_update(Nullable<int> id, string id_attributes, string name, string img, Nullable<int> id_attributeset, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at, Nullable<byte> active)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_attributesParameter = id_attributes != null ?
                new ObjectParameter("id_attributes", id_attributes) :
                new ObjectParameter("id_attributes", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var id_attributesetParameter = id_attributeset.HasValue ?
                new ObjectParameter("id_attributeset", id_attributeset) :
                new ObjectParameter("id_attributeset", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_attributes_update", idParameter, id_attributesParameter, nameParameter, imgParameter, id_attributesetParameter, create_atParameter, update_atParameter, activeParameter);
        }
    
        public virtual int sp_bill_delete(Nullable<int> id_bill)
        {
            var id_billParameter = id_bill.HasValue ?
                new ObjectParameter("id_bill", id_bill) :
                new ObjectParameter("id_bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_delete", id_billParameter);
        }
    
        public virtual int sp_bill_detail_delete(Nullable<int> id_bill_detail)
        {
            var id_bill_detailParameter = id_bill_detail.HasValue ?
                new ObjectParameter("id_bill_detail", id_bill_detail) :
                new ObjectParameter("id_bill_detail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_detail_delete", id_bill_detailParameter);
        }
    
        public virtual int sp_bill_detail_insert(Nullable<int> id_goods_attributes, Nullable<int> quantity, Nullable<int> id_bill)
        {
            var id_goods_attributesParameter = id_goods_attributes.HasValue ?
                new ObjectParameter("id_goods_attributes", id_goods_attributes) :
                new ObjectParameter("id_goods_attributes", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var id_billParameter = id_bill.HasValue ?
                new ObjectParameter("id_bill", id_bill) :
                new ObjectParameter("id_bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_detail_insert", id_goods_attributesParameter, quantityParameter, id_billParameter);
        }
    
        public virtual ObjectResult<sp_bill_detail_select_Result> sp_bill_detail_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bill_detail_select_Result>("sp_bill_detail_select");
        }
    
        public virtual int sp_bill_detail_update(Nullable<int> id_bill_detail, Nullable<int> id_goods_attributes, Nullable<int> quantity, Nullable<int> id_bill)
        {
            var id_bill_detailParameter = id_bill_detail.HasValue ?
                new ObjectParameter("id_bill_detail", id_bill_detail) :
                new ObjectParameter("id_bill_detail", typeof(int));
    
            var id_goods_attributesParameter = id_goods_attributes.HasValue ?
                new ObjectParameter("id_goods_attributes", id_goods_attributes) :
                new ObjectParameter("id_goods_attributes", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var id_billParameter = id_bill.HasValue ?
                new ObjectParameter("id_bill", id_bill) :
                new ObjectParameter("id_bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_detail_update", id_bill_detailParameter, id_goods_attributesParameter, quantityParameter, id_billParameter);
        }
    
        public virtual int sp_bill_insert(Nullable<int> payment_bill, Nullable<System.DateTime> time_bill, string note_bill, Nullable<int> price_promote_bill, string code_promote_bill, Nullable<int> id_customer, Nullable<int> id_goods_to_attributes, Nullable<int> id_staff)
        {
            var payment_billParameter = payment_bill.HasValue ?
                new ObjectParameter("payment_bill", payment_bill) :
                new ObjectParameter("payment_bill", typeof(int));
    
            var time_billParameter = time_bill.HasValue ?
                new ObjectParameter("time_bill", time_bill) :
                new ObjectParameter("time_bill", typeof(System.DateTime));
    
            var note_billParameter = note_bill != null ?
                new ObjectParameter("note_bill", note_bill) :
                new ObjectParameter("note_bill", typeof(string));
    
            var price_promote_billParameter = price_promote_bill.HasValue ?
                new ObjectParameter("price_promote_bill", price_promote_bill) :
                new ObjectParameter("price_promote_bill", typeof(int));
    
            var code_promote_billParameter = code_promote_bill != null ?
                new ObjectParameter("code_promote_bill", code_promote_bill) :
                new ObjectParameter("code_promote_bill", typeof(string));
    
            var id_customerParameter = id_customer.HasValue ?
                new ObjectParameter("id_customer", id_customer) :
                new ObjectParameter("id_customer", typeof(int));
    
            var id_goods_to_attributesParameter = id_goods_to_attributes.HasValue ?
                new ObjectParameter("id_goods_to_attributes", id_goods_to_attributes) :
                new ObjectParameter("id_goods_to_attributes", typeof(int));
    
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_insert", payment_billParameter, time_billParameter, note_billParameter, price_promote_billParameter, code_promote_billParameter, id_customerParameter, id_goods_to_attributesParameter, id_staffParameter);
        }
    
        public virtual ObjectResult<sp_bill_select_Result> sp_bill_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bill_select_Result>("sp_bill_select");
        }
    
        public virtual int sp_bill_update(Nullable<int> id_bill, Nullable<int> payment_bill, Nullable<System.DateTime> time_bill, string note_bill, Nullable<int> price_promote_bill, string code_promote_bill, Nullable<int> id_customer, Nullable<int> id_goods_to_attributes, Nullable<int> id_staff)
        {
            var id_billParameter = id_bill.HasValue ?
                new ObjectParameter("id_bill", id_bill) :
                new ObjectParameter("id_bill", typeof(int));
    
            var payment_billParameter = payment_bill.HasValue ?
                new ObjectParameter("payment_bill", payment_bill) :
                new ObjectParameter("payment_bill", typeof(int));
    
            var time_billParameter = time_bill.HasValue ?
                new ObjectParameter("time_bill", time_bill) :
                new ObjectParameter("time_bill", typeof(System.DateTime));
    
            var note_billParameter = note_bill != null ?
                new ObjectParameter("note_bill", note_bill) :
                new ObjectParameter("note_bill", typeof(string));
    
            var price_promote_billParameter = price_promote_bill.HasValue ?
                new ObjectParameter("price_promote_bill", price_promote_bill) :
                new ObjectParameter("price_promote_bill", typeof(int));
    
            var code_promote_billParameter = code_promote_bill != null ?
                new ObjectParameter("code_promote_bill", code_promote_bill) :
                new ObjectParameter("code_promote_bill", typeof(string));
    
            var id_customerParameter = id_customer.HasValue ?
                new ObjectParameter("id_customer", id_customer) :
                new ObjectParameter("id_customer", typeof(int));
    
            var id_goods_to_attributesParameter = id_goods_to_attributes.HasValue ?
                new ObjectParameter("id_goods_to_attributes", id_goods_to_attributes) :
                new ObjectParameter("id_goods_to_attributes", typeof(int));
    
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bill_update", id_billParameter, payment_billParameter, time_billParameter, note_billParameter, price_promote_billParameter, code_promote_billParameter, id_customerParameter, id_goods_to_attributesParameter, id_staffParameter);
        }
    
        public virtual int sp_categories_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_categories_delete", idParameter);
        }
    
        public virtual int sp_categories_insert(string id_categories, string name, Nullable<int> id_parent, Nullable<byte> sex, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_categoriesParameter = id_categories != null ?
                new ObjectParameter("id_categories", id_categories) :
                new ObjectParameter("id_categories", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var id_parentParameter = id_parent.HasValue ?
                new ObjectParameter("id_parent", id_parent) :
                new ObjectParameter("id_parent", typeof(int));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(byte));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_categories_insert", id_categoriesParameter, nameParameter, id_parentParameter, sexParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_categories_select_Result> sp_categories_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_categories_select_Result>("sp_categories_select");
        }
    
        public virtual int sp_categories_update(Nullable<int> id, string id_categories, string name, Nullable<int> id_parent, Nullable<byte> sex, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_categoriesParameter = id_categories != null ?
                new ObjectParameter("id_categories", id_categories) :
                new ObjectParameter("id_categories", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var id_parentParameter = id_parent.HasValue ?
                new ObjectParameter("id_parent", id_parent) :
                new ObjectParameter("id_parent", typeof(int));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(byte));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_categories_update", idParameter, id_categoriesParameter, nameParameter, id_parentParameter, sexParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_customer_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_customer_delete", idParameter);
        }
    
        public virtual int sp_customer_insert(string id_customer, string name_customer, string phone, string email, string address_, string id_tax, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_customerParameter = id_customer != null ?
                new ObjectParameter("id_customer", id_customer) :
                new ObjectParameter("id_customer", typeof(string));
    
            var name_customerParameter = name_customer != null ?
                new ObjectParameter("name_customer", name_customer) :
                new ObjectParameter("name_customer", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address_Parameter = address_ != null ?
                new ObjectParameter("address_", address_) :
                new ObjectParameter("address_", typeof(string));
    
            var id_taxParameter = id_tax != null ?
                new ObjectParameter("id_tax", id_tax) :
                new ObjectParameter("id_tax", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_customer_insert", id_customerParameter, name_customerParameter, phoneParameter, emailParameter, address_Parameter, id_taxParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<customer> sp_customer_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customer>("sp_customer_select");
        }
    
        public virtual ObjectResult<customer> sp_customer_select(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customer>("sp_customer_select", mergeOption);
        }
    
        public virtual int sp_customer_update(Nullable<int> id, string id_customer, string name_customer, string phone, string email, string address_, string id_tax, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_customerParameter = id_customer != null ?
                new ObjectParameter("id_customer", id_customer) :
                new ObjectParameter("id_customer", typeof(string));
    
            var name_customerParameter = name_customer != null ?
                new ObjectParameter("name_customer", name_customer) :
                new ObjectParameter("name_customer", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address_Parameter = address_ != null ?
                new ObjectParameter("address_", address_) :
                new ObjectParameter("address_", typeof(string));
    
            var id_taxParameter = id_tax != null ?
                new ObjectParameter("id_tax", id_tax) :
                new ObjectParameter("id_tax", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_customer_update", idParameter, id_customerParameter, name_customerParameter, phoneParameter, emailParameter, address_Parameter, id_taxParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_goods_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_delete", idParameter);
        }
    
        public virtual int sp_goods_insert(string id_goods, string name, string alias, Nullable<long> historycal_cost, Nullable<long> price, string img_thumb, Nullable<int> categories_id, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_goodsParameter = id_goods != null ?
                new ObjectParameter("id_goods", id_goods) :
                new ObjectParameter("id_goods", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var aliasParameter = alias != null ?
                new ObjectParameter("alias", alias) :
                new ObjectParameter("alias", typeof(string));
    
            var historycal_costParameter = historycal_cost.HasValue ?
                new ObjectParameter("historycal_cost", historycal_cost) :
                new ObjectParameter("historycal_cost", typeof(long));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(long));
    
            var img_thumbParameter = img_thumb != null ?
                new ObjectParameter("img_thumb", img_thumb) :
                new ObjectParameter("img_thumb", typeof(string));
    
            var categories_idParameter = categories_id.HasValue ?
                new ObjectParameter("categories_id", categories_id) :
                new ObjectParameter("categories_id", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_insert", id_goodsParameter, nameParameter, aliasParameter, historycal_costParameter, priceParameter, img_thumbParameter, categories_idParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_goods_select_Result> sp_goods_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_goods_select_Result>("sp_goods_select");
        }
    
        public virtual int sp_goods_to_attributes_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_to_attributes_delete", idParameter);
        }
    
        public virtual int sp_goods_to_attributes_insert(Nullable<int> id_goods, Nullable<int> id_attributes, Nullable<int> id_group_goods_attributes, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_goodsParameter = id_goods.HasValue ?
                new ObjectParameter("id_goods", id_goods) :
                new ObjectParameter("id_goods", typeof(int));
    
            var id_attributesParameter = id_attributes.HasValue ?
                new ObjectParameter("id_attributes", id_attributes) :
                new ObjectParameter("id_attributes", typeof(int));
    
            var id_group_goods_attributesParameter = id_group_goods_attributes.HasValue ?
                new ObjectParameter("id_group_goods_attributes", id_group_goods_attributes) :
                new ObjectParameter("id_group_goods_attributes", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_to_attributes_insert", id_goodsParameter, id_attributesParameter, id_group_goods_attributesParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_goods_to_attributes_select_Result> sp_goods_to_attributes_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_goods_to_attributes_select_Result>("sp_goods_to_attributes_select");
        }
    
        public virtual int sp_goods_to_attributes_update(Nullable<int> id, Nullable<int> id_goods, Nullable<int> id_attributes, Nullable<int> id_group_goods_attributes, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_goodsParameter = id_goods.HasValue ?
                new ObjectParameter("id_goods", id_goods) :
                new ObjectParameter("id_goods", typeof(int));
    
            var id_attributesParameter = id_attributes.HasValue ?
                new ObjectParameter("id_attributes", id_attributes) :
                new ObjectParameter("id_attributes", typeof(int));
    
            var id_group_goods_attributesParameter = id_group_goods_attributes.HasValue ?
                new ObjectParameter("id_group_goods_attributes", id_group_goods_attributes) :
                new ObjectParameter("id_group_goods_attributes", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_to_attributes_update", idParameter, id_goodsParameter, id_attributesParameter, id_group_goods_attributesParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_goods_update(Nullable<int> id, string id_goods, string name, string alias, Nullable<long> historycal_cost, Nullable<long> price, string img_thumb, Nullable<int> categories_id, Nullable<byte> active, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_goodsParameter = id_goods != null ?
                new ObjectParameter("id_goods", id_goods) :
                new ObjectParameter("id_goods", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var aliasParameter = alias != null ?
                new ObjectParameter("alias", alias) :
                new ObjectParameter("alias", typeof(string));
    
            var historycal_costParameter = historycal_cost.HasValue ?
                new ObjectParameter("historycal_cost", historycal_cost) :
                new ObjectParameter("historycal_cost", typeof(long));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(long));
    
            var img_thumbParameter = img_thumb != null ?
                new ObjectParameter("img_thumb", img_thumb) :
                new ObjectParameter("img_thumb", typeof(string));
    
            var categories_idParameter = categories_id.HasValue ?
                new ObjectParameter("categories_id", categories_id) :
                new ObjectParameter("categories_id", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_goods_update", idParameter, id_goodsParameter, nameParameter, aliasParameter, historycal_costParameter, priceParameter, img_thumbParameter, categories_idParameter, activeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_group_goods_quantity_stock_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_goods_quantity_stock_delete", idParameter);
        }
    
        public virtual int sp_group_goods_quantity_stock_insert(string id_group_goods_attributes, Nullable<long> add_sub_cost, Nullable<int> quantity, Nullable<int> id_stock, string barcode, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_group_goods_attributesParameter = id_group_goods_attributes != null ?
                new ObjectParameter("id_group_goods_attributes", id_group_goods_attributes) :
                new ObjectParameter("id_group_goods_attributes", typeof(string));
    
            var add_sub_costParameter = add_sub_cost.HasValue ?
                new ObjectParameter("add_sub_cost", add_sub_cost) :
                new ObjectParameter("add_sub_cost", typeof(long));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var id_stockParameter = id_stock.HasValue ?
                new ObjectParameter("id_stock", id_stock) :
                new ObjectParameter("id_stock", typeof(int));
    
            var barcodeParameter = barcode != null ?
                new ObjectParameter("barcode", barcode) :
                new ObjectParameter("barcode", typeof(string));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_goods_quantity_stock_insert", id_group_goods_attributesParameter, add_sub_costParameter, quantityParameter, id_stockParameter, barcodeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_group_goods_quantity_stock_select_Result> sp_group_goods_quantity_stock_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_goods_quantity_stock_select_Result>("sp_group_goods_quantity_stock_select");
        }
    
        public virtual int sp_group_goods_quantity_stock_update(Nullable<int> id, string id_group_goods_attributes, Nullable<long> add_sub_cost, Nullable<int> quantity, Nullable<int> id_stock, string barcode, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_group_goods_attributesParameter = id_group_goods_attributes != null ?
                new ObjectParameter("id_group_goods_attributes", id_group_goods_attributes) :
                new ObjectParameter("id_group_goods_attributes", typeof(string));
    
            var add_sub_costParameter = add_sub_cost.HasValue ?
                new ObjectParameter("add_sub_cost", add_sub_cost) :
                new ObjectParameter("add_sub_cost", typeof(long));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var id_stockParameter = id_stock.HasValue ?
                new ObjectParameter("id_stock", id_stock) :
                new ObjectParameter("id_stock", typeof(int));
    
            var barcodeParameter = barcode != null ?
                new ObjectParameter("barcode", barcode) :
                new ObjectParameter("barcode", typeof(string));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_goods_quantity_stock_update", idParameter, id_group_goods_attributesParameter, add_sub_costParameter, quantityParameter, id_stockParameter, barcodeParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_group_outpound_goods_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_outpound_goods_delete", idParameter);
        }
    
        public virtual int sp_group_outpound_goods_insert(Nullable<int> id_outbound, Nullable<int> id_group_goods_quantity_stock, Nullable<int> quantity_plan, Nullable<int> quantity_return, Nullable<int> quantity_output, Nullable<int> reason_return, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var id_outboundParameter = id_outbound.HasValue ?
                new ObjectParameter("id_outbound", id_outbound) :
                new ObjectParameter("id_outbound", typeof(int));
    
            var id_group_goods_quantity_stockParameter = id_group_goods_quantity_stock.HasValue ?
                new ObjectParameter("id_group_goods_quantity_stock", id_group_goods_quantity_stock) :
                new ObjectParameter("id_group_goods_quantity_stock", typeof(int));
    
            var quantity_planParameter = quantity_plan.HasValue ?
                new ObjectParameter("quantity_plan", quantity_plan) :
                new ObjectParameter("quantity_plan", typeof(int));
    
            var quantity_returnParameter = quantity_return.HasValue ?
                new ObjectParameter("quantity_return", quantity_return) :
                new ObjectParameter("quantity_return", typeof(int));
    
            var quantity_outputParameter = quantity_output.HasValue ?
                new ObjectParameter("quantity_output", quantity_output) :
                new ObjectParameter("quantity_output", typeof(int));
    
            var reason_returnParameter = reason_return.HasValue ?
                new ObjectParameter("reason_return", reason_return) :
                new ObjectParameter("reason_return", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_outpound_goods_insert", id_outboundParameter, id_group_goods_quantity_stockParameter, quantity_planParameter, quantity_returnParameter, quantity_outputParameter, reason_returnParameter, create_atParameter, update_atParameter);
        }
    
        public virtual ObjectResult<sp_group_outpound_goods_select_Result> sp_group_outpound_goods_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_outpound_goods_select_Result>("sp_group_outpound_goods_select");
        }
    
        public virtual int sp_group_outpound_goods_update(Nullable<int> id, Nullable<int> id_outbound, Nullable<int> id_group_goods_quantity_stock, Nullable<int> quantity_plan, Nullable<int> quantity_return, Nullable<int> quantity_output, Nullable<int> reason_return, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_outboundParameter = id_outbound.HasValue ?
                new ObjectParameter("id_outbound", id_outbound) :
                new ObjectParameter("id_outbound", typeof(int));
    
            var id_group_goods_quantity_stockParameter = id_group_goods_quantity_stock.HasValue ?
                new ObjectParameter("id_group_goods_quantity_stock", id_group_goods_quantity_stock) :
                new ObjectParameter("id_group_goods_quantity_stock", typeof(int));
    
            var quantity_planParameter = quantity_plan.HasValue ?
                new ObjectParameter("quantity_plan", quantity_plan) :
                new ObjectParameter("quantity_plan", typeof(int));
    
            var quantity_returnParameter = quantity_return.HasValue ?
                new ObjectParameter("quantity_return", quantity_return) :
                new ObjectParameter("quantity_return", typeof(int));
    
            var quantity_outputParameter = quantity_output.HasValue ?
                new ObjectParameter("quantity_output", quantity_output) :
                new ObjectParameter("quantity_output", typeof(int));
    
            var reason_returnParameter = reason_return.HasValue ?
                new ObjectParameter("reason_return", reason_return) :
                new ObjectParameter("reason_return", typeof(int));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_outpound_goods_update", idParameter, id_outboundParameter, id_group_goods_quantity_stockParameter, quantity_planParameter, quantity_returnParameter, quantity_outputParameter, reason_returnParameter, create_atParameter, update_atParameter);
        }
    
        public virtual int sp_outbound_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_outbound_delete", idParameter);
        }
    
        public virtual int sp_outbound_insert(Nullable<int> id_outbound, Nullable<int> id_staff, Nullable<int> id_staff_drive, string noted, Nullable<byte> status_, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at, Nullable<byte> active, Nullable<int> id_agency)
        {
            var id_outboundParameter = id_outbound.HasValue ?
                new ObjectParameter("id_outbound", id_outbound) :
                new ObjectParameter("id_outbound", typeof(int));
    
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            var id_staff_driveParameter = id_staff_drive.HasValue ?
                new ObjectParameter("id_staff_drive", id_staff_drive) :
                new ObjectParameter("id_staff_drive", typeof(int));
    
            var notedParameter = noted != null ?
                new ObjectParameter("noted", noted) :
                new ObjectParameter("noted", typeof(string));
    
            var status_Parameter = status_.HasValue ?
                new ObjectParameter("status_", status_) :
                new ObjectParameter("status_", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var id_agencyParameter = id_agency.HasValue ?
                new ObjectParameter("id_agency", id_agency) :
                new ObjectParameter("id_agency", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_outbound_insert", id_outboundParameter, id_staffParameter, id_staff_driveParameter, notedParameter, status_Parameter, create_atParameter, update_atParameter, activeParameter, id_agencyParameter);
        }
    
        public virtual ObjectResult<sp_outbound_select_Result> sp_outbound_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_outbound_select_Result>("sp_outbound_select");
        }
    
        public virtual int sp_outbound_update(Nullable<int> id, Nullable<int> id_outbound, Nullable<int> id_staff, Nullable<int> id_staff_drive, string noted, Nullable<byte> status_, Nullable<System.DateTime> create_at, Nullable<System.DateTime> update_at, Nullable<byte> active, Nullable<int> id_agency)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_outboundParameter = id_outbound.HasValue ?
                new ObjectParameter("id_outbound", id_outbound) :
                new ObjectParameter("id_outbound", typeof(int));
    
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            var id_staff_driveParameter = id_staff_drive.HasValue ?
                new ObjectParameter("id_staff_drive", id_staff_drive) :
                new ObjectParameter("id_staff_drive", typeof(int));
    
            var notedParameter = noted != null ?
                new ObjectParameter("noted", noted) :
                new ObjectParameter("noted", typeof(string));
    
            var status_Parameter = status_.HasValue ?
                new ObjectParameter("status_", status_) :
                new ObjectParameter("status_", typeof(byte));
    
            var create_atParameter = create_at.HasValue ?
                new ObjectParameter("create_at", create_at) :
                new ObjectParameter("create_at", typeof(System.DateTime));
    
            var update_atParameter = update_at.HasValue ?
                new ObjectParameter("update_at", update_at) :
                new ObjectParameter("update_at", typeof(System.DateTime));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(byte));
    
            var id_agencyParameter = id_agency.HasValue ?
                new ObjectParameter("id_agency", id_agency) :
                new ObjectParameter("id_agency", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_outbound_update", idParameter, id_outboundParameter, id_staffParameter, id_staff_driveParameter, notedParameter, status_Parameter, create_atParameter, update_atParameter, activeParameter, id_agencyParameter);
        }
    
        public virtual int sp_role_staff_delete(Nullable<int> id_role)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_role_staff_delete", id_roleParameter);
        }
    
        public virtual int sp_role_staff_insert(string name_role)
        {
            var name_roleParameter = name_role != null ?
                new ObjectParameter("name_role", name_role) :
                new ObjectParameter("name_role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_role_staff_insert", name_roleParameter);
        }
    
        public virtual ObjectResult<sp_role_staff_select_Result> sp_role_staff_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_role_staff_select_Result>("sp_role_staff_select");
        }
    
        public virtual int sp_role_staff_update(Nullable<int> id_role, string name_role)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var name_roleParameter = name_role != null ?
                new ObjectParameter("name_role", name_role) :
                new ObjectParameter("name_role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_role_staff_update", id_roleParameter, name_roleParameter);
        }
    
        public virtual int sp_staff_delete(Nullable<int> id_staff)
        {
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_staff_delete", id_staffParameter);
        }
    
        public virtual int sp_staff_insert(Nullable<System.DateTime> birthday_staff, string name_staff, string username_staff, string pass_staff, string address_staff, string mobile_staff, Nullable<int> id_role)
        {
            var birthday_staffParameter = birthday_staff.HasValue ?
                new ObjectParameter("birthday_staff", birthday_staff) :
                new ObjectParameter("birthday_staff", typeof(System.DateTime));
    
            var name_staffParameter = name_staff != null ?
                new ObjectParameter("name_staff", name_staff) :
                new ObjectParameter("name_staff", typeof(string));
    
            var username_staffParameter = username_staff != null ?
                new ObjectParameter("username_staff", username_staff) :
                new ObjectParameter("username_staff", typeof(string));
    
            var pass_staffParameter = pass_staff != null ?
                new ObjectParameter("pass_staff", pass_staff) :
                new ObjectParameter("pass_staff", typeof(string));
    
            var address_staffParameter = address_staff != null ?
                new ObjectParameter("address_staff", address_staff) :
                new ObjectParameter("address_staff", typeof(string));
    
            var mobile_staffParameter = mobile_staff != null ?
                new ObjectParameter("mobile_staff", mobile_staff) :
                new ObjectParameter("mobile_staff", typeof(string));
    
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_staff_insert", birthday_staffParameter, name_staffParameter, username_staffParameter, pass_staffParameter, address_staffParameter, mobile_staffParameter, id_roleParameter);
        }
    
        public virtual ObjectResult<staff> sp_staff_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<staff>("sp_staff_select");
        }
    
        public virtual ObjectResult<staff> sp_staff_select(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<staff>("sp_staff_select", mergeOption);
        }
    
        public virtual int sp_staff_update(Nullable<int> id_staff, Nullable<System.DateTime> birthday_staff, string name_staff, string username_staff, string pass_staff, string address_staff, string mobile_staff, Nullable<int> id_role)
        {
            var id_staffParameter = id_staff.HasValue ?
                new ObjectParameter("id_staff", id_staff) :
                new ObjectParameter("id_staff", typeof(int));
    
            var birthday_staffParameter = birthday_staff.HasValue ?
                new ObjectParameter("birthday_staff", birthday_staff) :
                new ObjectParameter("birthday_staff", typeof(System.DateTime));
    
            var name_staffParameter = name_staff != null ?
                new ObjectParameter("name_staff", name_staff) :
                new ObjectParameter("name_staff", typeof(string));
    
            var username_staffParameter = username_staff != null ?
                new ObjectParameter("username_staff", username_staff) :
                new ObjectParameter("username_staff", typeof(string));
    
            var pass_staffParameter = pass_staff != null ?
                new ObjectParameter("pass_staff", pass_staff) :
                new ObjectParameter("pass_staff", typeof(string));
    
            var address_staffParameter = address_staff != null ?
                new ObjectParameter("address_staff", address_staff) :
                new ObjectParameter("address_staff", typeof(string));
    
            var mobile_staffParameter = mobile_staff != null ?
                new ObjectParameter("mobile_staff", mobile_staff) :
                new ObjectParameter("mobile_staff", typeof(string));
    
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_staff_update", id_staffParameter, birthday_staffParameter, name_staffParameter, username_staffParameter, pass_staffParameter, address_staffParameter, mobile_staffParameter, id_roleParameter);
        }
    
        public virtual int sp_state_bill_delete(Nullable<int> id_role)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_bill_delete", id_roleParameter);
        }
    
        public virtual int sp_state_bill_insert(string name_role)
        {
            var name_roleParameter = name_role != null ?
                new ObjectParameter("name_role", name_role) :
                new ObjectParameter("name_role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_bill_insert", name_roleParameter);
        }
    
        public virtual ObjectResult<sp_state_bill_select_Result> sp_state_bill_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_bill_select_Result>("sp_state_bill_select");
        }
    
        public virtual int sp_state_bill_update(Nullable<int> id_role, string name_role)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var name_roleParameter = name_role != null ?
                new ObjectParameter("name_role", name_role) :
                new ObjectParameter("name_role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_bill_update", id_roleParameter, name_roleParameter);
        }
    
        public virtual int sp_state_goods_delete(Nullable<int> id_state)
        {
            var id_stateParameter = id_state.HasValue ?
                new ObjectParameter("id_state", id_state) :
                new ObjectParameter("id_state", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_goods_delete", id_stateParameter);
        }
    
        public virtual int sp_state_goods_insert(string name_state)
        {
            var name_stateParameter = name_state != null ?
                new ObjectParameter("name_state", name_state) :
                new ObjectParameter("name_state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_goods_insert", name_stateParameter);
        }
    
        public virtual ObjectResult<sp_state_goods_select_Result> sp_state_goods_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_goods_select_Result>("sp_state_goods_select");
        }
    
        public virtual int sp_state_goods_update(Nullable<int> id_state, string name_state)
        {
            var id_stateParameter = id_state.HasValue ?
                new ObjectParameter("id_state", id_state) :
                new ObjectParameter("id_state", typeof(int));
    
            var name_stateParameter = name_state != null ?
                new ObjectParameter("name_state", name_state) :
                new ObjectParameter("name_state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_state_goods_update", id_stateParameter, name_stateParameter);
        }
    
        public virtual ObjectResult<sp_attributes_search_Result> sp_attributes_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_attributes_search_Result>("sp_attributes_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_attributes_set_search_Result> sp_attributes_set_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_attributes_set_search_Result>("sp_attributes_set_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_bill_detail_search_Result> sp_bill_detail_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bill_detail_search_Result>("sp_bill_detail_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_bill_search_Result> sp_bill_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bill_search_Result>("sp_bill_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_categories_search_Result> sp_categories_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_categories_search_Result>("sp_categories_search", key_searchParameter);
        }
    
        public virtual ObjectResult<customer> sp_customer_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customer>("sp_customer_search", key_searchParameter);
        }
    
        public virtual ObjectResult<customer> sp_customer_search(string key_search, MergeOption mergeOption)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customer>("sp_customer_search", mergeOption, key_searchParameter);
        }
    
        public virtual ObjectResult<sp_goods_search_Result> sp_goods_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_goods_search_Result>("sp_goods_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_goods_to_attributes_search_Result> sp_goods_to_attributes_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_goods_to_attributes_search_Result>("sp_goods_to_attributes_search", key_searchParameter);
        }
    
        public virtual int sp_group_agency_goods_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_agency_goods_delete", idParameter);
        }
    
        public virtual int sp_group_agency_goods_insert(Nullable<int> id_agency, Nullable<int> id_group_goods, Nullable<int> quanity)
        {
            var id_agencyParameter = id_agency.HasValue ?
                new ObjectParameter("id_agency", id_agency) :
                new ObjectParameter("id_agency", typeof(int));
    
            var id_group_goodsParameter = id_group_goods.HasValue ?
                new ObjectParameter("id_group_goods", id_group_goods) :
                new ObjectParameter("id_group_goods", typeof(int));
    
            var quanityParameter = quanity.HasValue ?
                new ObjectParameter("quanity", quanity) :
                new ObjectParameter("quanity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_agency_goods_insert", id_agencyParameter, id_group_goodsParameter, quanityParameter);
        }
    
        public virtual ObjectResult<sp_group_agency_goods_search_Result> sp_group_agency_goods_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_agency_goods_search_Result>("sp_group_agency_goods_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_group_agency_goods_select_Result> sp_group_agency_goods_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_agency_goods_select_Result>("sp_group_agency_goods_select");
        }
    
        public virtual int sp_group_agency_goods_update(Nullable<int> id, Nullable<int> id_agency, Nullable<int> id_group_goods, Nullable<int> quanity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_agencyParameter = id_agency.HasValue ?
                new ObjectParameter("id_agency", id_agency) :
                new ObjectParameter("id_agency", typeof(int));
    
            var id_group_goodsParameter = id_group_goods.HasValue ?
                new ObjectParameter("id_group_goods", id_group_goods) :
                new ObjectParameter("id_group_goods", typeof(int));
    
            var quanityParameter = quanity.HasValue ?
                new ObjectParameter("quanity", quanity) :
                new ObjectParameter("quanity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_group_agency_goods_update", idParameter, id_agencyParameter, id_group_goodsParameter, quanityParameter);
        }
    
        public virtual ObjectResult<sp_group_goods_quantity_stock_search_Result> sp_group_goods_quantity_stock_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_goods_quantity_stock_search_Result>("sp_group_goods_quantity_stock_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_group_outpound_goods_search_Result> sp_group_outpound_goods_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_outpound_goods_search_Result>("sp_group_outpound_goods_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_outbound_search_Result> sp_outbound_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_outbound_search_Result>("sp_outbound_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_role_staff_search_Result> sp_role_staff_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_role_staff_search_Result>("sp_role_staff_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_staff_search_Result> sp_staff_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_staff_search_Result>("sp_staff_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_state_bill_search_Result> sp_state_bill_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_bill_search_Result>("sp_state_bill_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_state_ebill_search_Result> sp_state_ebill_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_ebill_search_Result>("sp_state_ebill_search", key_searchParameter);
        }
    
        public virtual ObjectResult<sp_state_goods_search_Result> sp_state_goods_search(string key_search)
        {
            var key_searchParameter = key_search != null ?
                new ObjectParameter("key_search", key_search) :
                new ObjectParameter("key_search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_goods_search_Result>("sp_state_goods_search", key_searchParameter);
        }
    }
}
