//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_agency_goods
    {
        public int id { get; set; }
        public int id_agency { get; set; }
        public int id_group_goods { get; set; }
        public int quanity { get; set; }
    
        public virtual group_goods_quantity_stock group_goods_quantity_stock { get; set; }
    }
}
