//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_goods_quantity_stock
    {
        public group_goods_quantity_stock()
        {
            this.goods_to_attributes = new HashSet<goods_to_attributes>();
            this.group_outpound_goods = new HashSet<group_outpound_goods>();
            this.group_agency_goods = new HashSet<group_agency_goods>();
        }
    
        public int id { get; set; }
        public string id_group_goods_attributes { get; set; }
        public long add_sub_cost { get; set; }
        public int quantity { get; set; }
        public int id_stock { get; set; }
        public string barcode { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    
        public virtual ICollection<goods_to_attributes> goods_to_attributes { get; set; }
        public virtual ICollection<group_outpound_goods> group_outpound_goods { get; set; }
        public virtual ICollection<group_agency_goods> group_agency_goods { get; set; }
    }
}
