//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_staff
    {
        public role_staff()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int id_role { get; set; }
        public string name_role { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
    }
}
