//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_Pannel.Data_Acess
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.bills = new HashSet<bill>();
            this.outbounds = new HashSet<outbound>();
        }
    
        public int id_staff { get; set; }
        public Nullable<System.DateTime> birthday_staff { get; set; }
        public string name_staff { get; set; }
        public string username_staff { get; set; }
        public string pass_staff { get; set; }
        public string address_staff { get; set; }
        public string mobile_staff { get; set; }
        public int id_role { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
        public virtual ICollection<outbound> outbounds { get; set; }
        public virtual role_staff role_staff { get; set; }
    }
}
